"""updated slugid to be a unique value

Revision ID: 3cb256c615f4
Revises: 
Create Date: 2026-02-06 15:50:42.222267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb256c615f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('spin', sa.Integer(), nullable=True),
    sa.Column('transferable', sa.Integer(), nullable=True),
    sa.Column('snapshotTimestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='objekt_db'
    )
    op.create_table('slugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slugId', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slugString', sa.String(), nullable=True),
    sa.Column('collectionId', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('member', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('collectionNo', sa.String(), nullable=True),
    sa.Column('className', sa.String(), nullable=True),
    sa.Column('frontImage', sa.String(), nullable=True),
    sa.Column('backImage', sa.String(), nullable=True),
    sa.Column('backgroundColor', sa.String(), nullable=True),
    sa.Column('textColor', sa.String(), nullable=True),
    sa.Column('onOffline', sa.String(), nullable=True),
    sa.Column('bandImageUrl', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slugId'),
    schema='objekt_db'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slugs', schema='objekt_db')
    op.drop_table('metadata_snapshots', schema='objekt_db')
    # ### end Alembic commands ###
