"""added slugs table

Revision ID: 80cc84081753
Revises: 
Create Date: 2026-02-04 20:45:07.737810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80cc84081753'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slugId', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slugString', sa.String(), nullable=True),
    sa.Column('collectionId', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('member', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('collectionNo', sa.String(), nullable=True),
    sa.Column('className', sa.String(), nullable=True),
    sa.Column('frontImage', sa.String(), nullable=True),
    sa.Column('backImage', sa.String(), nullable=True),
    sa.Column('backgroundColor', sa.String(), nullable=True),
    sa.Column('textColor', sa.String(), nullable=True),
    sa.Column('onOffline', sa.String(), nullable=True),
    sa.Column('bandImageUrl', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='objekt_db'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slugs', schema='objekt_db')
    # ### end Alembic commands ###
