"""added workbatch to collections table

Revision ID: c4adf2e2a6fc
Revises: 3cb256c615f4
Create Date: 2026-02-11 14:43:12.862084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4adf2e2a6fc'
down_revision: Union[str, Sequence[str], None] = '3cb256c615f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slugs', sa.Column('workBatch', sa.Integer(), nullable=True), schema='objekt_db')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slugs', 'workBatch', schema='objekt_db')
    # ### end Alembic commands ###
